### ISSUE TITLE
Can't build with GCC 4.3 and 4.5

### ISSUE THREAD

**Issue by Zenitur** [Oblomov/clinfo#33]
With 4.8 it builds fine. https://build.opensuse.org/package/show/home:linux4humans:wine-staging/clinfo

```
cc -fomit-frame-pointer -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -std=c99 -g -Wall -Wextra -pedantic -Werror   -c -o clinfo.o src/clinfo.c
cc1: warnings being treated as errors
src/clinfo.c: In function 'oclIcdProps':
src/clinfo.c:2689:2: error: dereferencing type-punned pointer will break strict-aliasing rules
make: *** [clinfo.o] Error 1
```

**Comment by Oblomov** [comment]
Should be fixed in master now, Can you give it a go and verify, please?

**Comment by Zenitur** [comment]
Now it's compiling with GCC 4.3 and 4.5.

**Comment by Oblomov** [comment]
Thanks, closing the issue now.
